# Generated by Django 3.1.1 on 2022-04-11 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingNumber', models.CharField(max_length=150, null=True)),
                ('Remark', models.CharField(max_length=250, null=True)),
                ('Status', models.CharField(max_length=150, null=True)),
                ('UpdationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DriverID', models.CharField(max_length=150, null=True)),
                ('MobileNumber', models.CharField(max_length=15, null=True)),
                ('Address', models.CharField(max_length=150, null=True)),
                ('JoiningDate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BookingNumber', models.CharField(max_length=150, null=True)),
                ('PhoneNumber', models.CharField(max_length=15, null=True)),
                ('PickupLoc', models.CharField(max_length=150, null=True)),
                ('Destination', models.CharField(max_length=200, null=True)),
                ('PickupDate', models.DateField(null=True)),
                ('PickupTime', models.TimeField(null=True)),
                ('DateofRequest', models.DateTimeField(auto_now_add=True)),
                ('Remark', models.CharField(max_length=250, null=True)),
                ('Status', models.CharField(max_length=150, null=True)),
                ('AssignTo', models.CharField(max_length=150, null=True)),
                ('UpdationDate', models.DateField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
