# Generated by Django 3.1.1 on 2022-04-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleassist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='DriverID',
            field=models.IntegerField(null=True),
        ),
    ]
