# Generated by Django 3.1.1 on 2022-04-12 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleassist', '0002_auto_20220411_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='BookingNumber',
        ),
        migrations.AddField(
            model_name='tracking',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleassist.book'),
        ),
    ]
