# Generated by Django 3.1.1 on 2022-04-12 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleassist', '0003_auto_20220412_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='AssignTo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicleassist.driver'),
        ),
    ]
